services:
 postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    ports:
      - "5432:5432"
    command: |
      postgres -c log_statement=all
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgresql://langchain:langchain@localhost/langchain --command 'SELECT 1;' || exit 1",
        ]
      interval: 5s
      retries: 60
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d/